// The override being edited: the saved text on disk and the unsaved draft, plus the save flow.
import { DATA, MODDIR, api, commitConfig, readFile, readFileIfExists, removeFiles, testConfig, writeFile } from './device.js';
import { countChanges } from './changes.js';
import { MergeError, merge } from './merge.js';
import { YAMLException, parse, stringify } from './yaml.js';

const OVERRIDE_TMP = `${DATA}/override.yaml.tmp`;
const CONFIG_TMP = `${DATA}/config.yaml.tmp`;
const CONFIG_HEADER = '# Generated by the mihomo-ksu WebUI from base.yaml + override.yaml; do not edit.\n';

// kind: 'yaml' | 'merge' | 'validate' (nothing written) or 'reload' (written but not applied).
export class SaveError extends Error {
  constructor(kind, detail) {
    super(kind);
    this.name = 'SaveError';
    this.kind = kind;
    this.detail = detail;
  }
}

let saved = '';
let draft = '';
const listeners = new Set();
const notify = () => listeners.forEach((fn) => fn());

export async function loadDraft() {
  saved = draft = await readFileIfExists(`${DATA}/override.yaml`);
  notify();
}

export const getDraft = () => draft;
export const isDirty = () => draft !== saved;
export const onDraftChange = (fn) => listeners.add(fn);

export function setDraft(text) {
  draft = text;
  notify();
}

export function discardDraft() {
  draft = saved;
  notify();
}

// null when the draft does not parse; the bar then shows no number.
export function changeCount() {
  try {
    return countChanges(parse(saved), parse(draft));
  } catch {
    return null;
  }
}

function parseOverride(text) {
  try {
    return parse(text);
  } catch (err) {
    if (err instanceof YAMLException) {
      throw new SaveError('yaml', { line: err.mark ? err.mark.line + 1 : null, message: err.message });
    }
    throw err;
  }
}

// The config.yaml text the draft would produce.
export async function buildConfig(text = draft) {
  const override = parseOverride(text);
  const base = parse(await readFile(`${MODDIR}/base.yaml`));
  try {
    return CONFIG_HEADER + stringify(merge(base, override));
  } catch (err) {
    if (err instanceof MergeError) throw new SaveError('merge', { code: err.code, params: err.params });
    throw err;
  }
}

export async function saveDraft() {
  const text = draft;
  const config = await buildConfig(text);
  await writeFile(OVERRIDE_TMP, text);
  await writeFile(CONFIG_TMP, config);
  const test = await testConfig(CONFIG_TMP);
  if (!test.ok) {
    await removeFiles(OVERRIDE_TMP, CONFIG_TMP);
    throw new SaveError('validate', { output: test.output });
  }
  await commitConfig(OVERRIDE_TMP, CONFIG_TMP);
  saved = text;
  notify();
  try {
    await api('PUT', '/configs?force=true', { path: '', payload: '' });
  } catch (err) {
    throw new SaveError('reload', { message: err.stderr || err.message });
  }
}
