// The override being edited: the saved text on disk and the unsaved draft, plus the save flow.
import { DATA, MODDIR, api, commitConfig, makeDir, readFile, readFileIfExists, removeFiles, testConfig, writeFile } from './device.js';
import { countChanges, deepEqual } from './changes.js';
import { MergeError, merge } from './merge.js';
import { YAMLException, parse, stringify } from './yaml.js';

const OVERRIDE_TMP = `${DATA}/override.yaml.tmp`;
const CONFIG_TMP = `${DATA}/config.yaml.tmp`;
const CONFIG_HEADER = '# Generated by the mihomo-ksu WebUI from base.yaml + override.yaml; do not edit.\n';

// kind: 'yaml' | 'merge' | 'validate' (nothing written) or 'reload' (written but not applied).
export class SaveError extends Error {
  constructor(kind, detail) {
    super(kind);
    this.name = 'SaveError';
    this.kind = kind;
    this.detail = detail;
  }
}

let saved = '';
let draft = '';
// Subscription name → { fileName, text, nodes } of a picked file, written to its path on save.
let files = new Map();
let base = null;
const listeners = new Set();
const notify = () => listeners.forEach((fn) => fn());

export async function loadDraft() {
  saved = draft = await readFileIfExists(`${DATA}/override.yaml`);
  notify();
}

export const getDraft = () => draft;
export const isDirty = () => draft !== saved || files.size > 0;
export const getFiles = () => new Map(files);

export function setFiles(next) {
  files = next;
  notify();
}
export const onDraftChange = (fn) => listeners.add(fn);

export function setDraft(text) {
  draft = text;
  notify();
}

// base.yaml only changes with a module upgrade, which needs a reboot, so parse it once.
export async function getBase() {
  base ??= parse(await readFile(`${MODDIR}/base.yaml`));
  return base;
}

// The parsed saved override and draft; throws when the draft does not parse.
export const parsedSaved = () => parse(saved);
export const parsedDraft = () => parse(draft);

// Applies a form edit: parse the draft, let fn return the new override, print it back.
// Comments in the draft are lost (docs/plans/c5-webui.md, 关键做法), except that an edit
// landing back on the saved content restores the saved text, so nothing shows as unsaved.
export function updateDraft(fn) {
  const next = fn(parse(draft));
  const empty = !next || Object.keys(next).length === 0;
  if (deepEqual(empty ? null : next, parse(saved))) draft = saved;
  else draft = empty ? '' : stringify(next);
  notify();
}

export function discardDraft() {
  draft = saved;
  files = new Map();
  notify();
}

// null when the draft does not parse; the bar then shows no number.
export function changeCount() {
  try {
    return countChanges(parse(saved), parse(draft), [...files.keys()]);
  } catch {
    return null;
  }
}

function parseOverride(text) {
  try {
    return parse(text);
  } catch (err) {
    if (err instanceof YAMLException) {
      throw new SaveError('yaml', { line: err.mark ? err.mark.line + 1 : null, message: err.message });
    }
    throw err;
  }
}

async function mergeOverride(text) {
  const override = parseOverride(text);
  try {
    return merge(await getBase(), override);
  } catch (err) {
    if (err instanceof MergeError) throw new SaveError('merge', { code: err.code, params: err.params });
    throw err;
  }
}

// The config.yaml text the draft would produce.
export async function buildConfig(text = draft) {
  return CONFIG_HEADER + stringify(await mergeOverride(text));
}

// Writes each picked file next to its path in the merged config (relative paths are under the
// data directory, mihomo's home) and returns the [tmp, path] moves that put them in place.
async function stageFiles(config, picked) {
  const moves = [];
  for (const [name, { text }] of picked) {
    // The subscription may have been removed in the YAML editor since its file was picked.
    const path = config['proxy-providers']?.[name]?.path;
    if (!path) continue;
    const target = path.startsWith('/') ? path : `${DATA}/${path.replace(/^\.\//, '')}`;
    await makeDir(target.slice(0, target.lastIndexOf('/')));
    await writeFile(`${target}.tmp`, text);
    moves.push([`${target}.tmp`, target]);
  }
  return moves;
}

export async function saveDraft() {
  const text = draft;
  const picked = files;
  const config = await mergeOverride(text);
  await writeFile(OVERRIDE_TMP, text);
  await writeFile(CONFIG_TMP, CONFIG_HEADER + stringify(config));
  // mihomo -t does not read type: file providers, so their files can follow the test.
  const test = await testConfig(CONFIG_TMP);
  if (!test.ok) {
    await removeFiles(OVERRIDE_TMP, CONFIG_TMP);
    throw new SaveError('validate', { output: test.output });
  }
  await commitConfig(OVERRIDE_TMP, CONFIG_TMP, await stageFiles(config, picked));
  saved = text;
  files = new Map();
  notify();
  try {
    await api('PUT', '/configs?force=true', { path: '', payload: '' });
  } catch (err) {
    throw new SaveError('reload', { message: err.stderr || err.message });
  }
}
